AddressCollector/Controllers/EnvelopeController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Security.Claims;
using AddressCollector.Data.Auth;
using AddressCollector.Data.DataContext;
using AddressCollector.Data.Entities;
using AddressCollector.Data.Repositories.Interfaces;
using AddressCollector.Models;
using AddressCollector.Shared;
using AddressCollector.ViewModels;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using PdfSharp;
using PdfSharp.Drawing;
using PdfSharp.Pdf;

namespace AddressCollector.Controllers
{
    
    public class EnvelopeController : Controller
    {
        private readonly IEnvelopeRepository _envelopeRepository;
        private readonly IMapper _mapper;
        private readonly UserManager<ApplicationUser> _userManager;
        
        public EnvelopeController(IEnvelopeRepository envelopeRepository, IMapper mapper, UserManager<ApplicationUser> userManager)
        {
            _envelopeRepository = envelopeRepository;
            _mapper = mapper;
            _userManager = userManager;
        }
        
        [Authorize(Roles="Administrator, Ondernemer")]
        // GET: /<controller>/
        public IActionResult Index()
        {
            var model = new EnvelopeListViewModel();

            var envelopes = _envelopeRepository.AllEnvelopes(User).ToList();

            foreach (var envelope in envelopes)
            {
                model.Envelopes.Add(_mapper.Map<EnvelopeViewModel>(envelopes));
            }
            
            return View();
        }

        [Authorize(Roles="Administrator, Ondernemer")]
        public IActionResult AddNewEnvelope()
        {
            var model = new EnvelopeViewModel();
            //set ondernemerId
            var user = _userManager.FindByNameAsync(User.Identity.Name);
            if (user.Result != null)
            {
                model.OndernemerId = user.Result.Id;
            }
            
            return View(model);
        }

        [Authorize(Roles="Administrator, Ondernemer")]
        [HttpPost]
        public IActionResult AddNewEnvelope(EnvelopeViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);
            
            var envelope = _mapper.Map<Envelope>(model);
            _envelopeRepository.Add(envelope);
            _envelopeRepository.Save();

            return RedirectToAction("EnvelopeManagement");
        }

        
        [Authorize(Roles="Administrator, Ondernemer")]
        public IActionResult EnvelopeManagement()
        {
            var model = new EnvelopeListViewModel();
            model.Envelopes = new List<EnvelopeViewModel>();
            model.Envelopes = _mapper.Map<List<EnvelopeViewModel>>(_envelopeRepository.AllEnvelopes(User).ToList());

            if (User.IsInRole(Constants.AdminUserRole))
            {
                foreach (var envelope in model.Envelopes)
                {
                    envelope.Ondernemer = _userManager.Users.FirstOrDefault(x => x.Id == envelope.OndernemerId);
                }
            }

            return View(model);
        }
        
        [Authorize(Roles="Administrator, Ondernemer")]
        public IActionResult DeleteEnvelope(int id)
        {
           //doe hier de delete
           var envelope = _envelopeRepository.GetEnvelopeById(id);
           _envelopeRepository.Delete(envelope);
           _envelopeRepository.Save();

            return RedirectToAction("EnvelopeManagement");
        }

        [Authorize(Roles="Administrator, Ondernemer")]
        public IActionResult EditEnvelope(int id)
        {
            var envelope = _envelopeRepository.GetEnvelopeById(id);
            var model = _mapper.Map<EnvelopeViewModel>(envelope);
            
            return View(model);
        }

        [Authorize(Roles="Administrator, Ondernemer")]
        [HttpPost]
        public IActionResult EditEnvelope(EnvelopeViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);
            
            var envelope = _mapper.Map<Envelope>(model);
            _envelopeRepository.Update(envelope);
            _envelopeRepository.Save();

            return RedirectToAction("EnvelopeManagement");
        }

        

        

        
        

        

        

        
    }
}

AddressCollector/Views/Envelope/AddNewEnvelope.cshtml
@model EnvelopeViewModel

<h2>Voer nieuwe envelop in</h2>

<form asp-controller="Envelope" asp-action="AddNewEnvelope" method="post" class="form-horizontal" role="form">
    <h4>Vul hieronder de details in</h4>
    <hr />
    
    @Html.HiddenFor(x => x.OndernemerId)
    
    <partial name="_envelopeFields"/>

    <div class="form-group">
        <div class="col-md-10">
            <input type="submit" class="btn btn-primary" value="Opslaan" title="Opslaan" />
            <a asp-action="EnvelopeManagement" class="btn btn-primary">Annuleren</a>
        </div>
    </div>
</form>

AddressCollector/Views/Envelope/EditEnvelope.cshtml
@model EnvelopeViewModel
@using Microsoft.AspNetCore.Mvc.Rendering;
<h2>Wijzig envelop</h2>

<form asp-controller="Envelope" asp-action="EditEnvelope" method="post" class="form-horizontal" role="form">
    <h4>U kunt de onderstaande gegevens wijzigen</h4>
    <hr />
    
    @Html.HiddenFor(x => x.OndernemerId)
    
    <partial name="_envelopeFields" />
    
    <div class="form-group">
        <div class="col-md-10">
            <input type="submit" class="btn btn-primary" value="Opslaan" />
            <a asp-action="EnvelopeManagement" class="btn btn-primary">Annuleren</a>
        </div>
    </div>
</form>

AddressCollector/Views/Envelope/EnvelopeManagement.cshtml
@using AddressCollector.Shared
@model EnvelopeListViewModel

<h2>Enveloppen beheer</h2>

@if (!Model.Envelopes.Any())
{
    <tr><td colspan="3" class="text-center">Geen enveloppen gevonden</td></tr>
    <br />
    <br />
}
else
{
    <table class="table table-condensed table-bordered" header header-content="Enveloppen beheer">
        <tr>
            <th>Naam</th>
            <th>Lengte</th>
            <th>Breedte</th>
            @if (User.IsInRole(Constants.AdminUserRole))
            {
                <th>Ondernemer</th>
            }
            <th>Acties</th>
        </tr>
        @foreach (var envelope in Model.Envelopes)
        {
            <tr>
                <td>@envelope.Naam</td>
                <td>@envelope.Lengte</td>
                <td>@envelope.Breedte</td>
                @if (User.IsInRole(Constants.AdminUserRole))
                {
                    <td>@envelope.Ondernemer.Naam</td>
                }
                <td>
                    <form asp-action="DeleteEnvelope" asp-route-Id="@envelope.Id" method="post">
                        <a class="btn btn-sm btn-primary" asp-action="EditEnvelope" asp-route-id="@envelope.Id">Wijzigen</a>
                        <button type="submit" onclick="return confirm('Weet u zeker dat u deze envelop?');" class="btn btn-sm btn-danger">Verwijderen</button>
                    </form>


                </td>
            </tr>
        }
    </table>
}

<a class="btn btn-primary" asp-action="AddNewEnvelope">Voeg nieuwe envelop toe</a>

AddressCollector/Views/Envelope/Index.cshtml
@model EnvelopeViewModel



<h2>Dit is het enveloppen overzicht!</h2>


<div class="row">

    @*@foreach (var pie in Model.PiesOfTheWeek)
    {
        <partial name="_PieCard" model="pie" />
    }*@

</div>

AddressCollector/Views/Envelope/_envelopeFields.cshtml
@using Microsoft.AspNetCore.Mvc.Rendering;
@model EnvelopeViewModel

@Html.HiddenFor(x => x.CreateDate)
@Html.HiddenFor(x => x.LastUpdateDate)

<div class="row">
    <div class="col-md-6">
        <div class="form-group">
            <label asp-for="Naam" class="col-md-2 control-label no-padding-left"></label>
            <input asp-for="Naam" class="form-control" placeholder="Naam" autocomplete="off" />
            <span asp-validation-for="Naam" class="text-danger"></span>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-3">
        <div class="form-group">
            <label asp-for="Lengte" class="control-label no-padding-left"></label>
            <input asp-for="Lengte" class="form-control" placeholder="Hoogte" autocomplete="off"/>
            <span asp-validation-for="Naam" class="text-danger"></span>
        </div>
    </div>
    <div class="col-md-3">
        <div class="form-group">
            <label asp-for="Breedte" class="control-label no-padding-left"></label>
            <input asp-for="Breedte" class="form-control" placeholder="Breedte" autocomplete="off"/>
            <span asp-validation-for="Breedte" class="text-danger"></span>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-3">
        <div class="form-group">
            <label asp-for="OffsetLinks" class="control-label"></label>
            <input asp-for="OffsetLinks" class="form-control" placeholder="Offset links" autocomplete="off"/>
        </div>
    </div>
    <div class="col-md-3">
        <div class="form-group">
            <label asp-for="OffsetTop" class="control-label no-padding-left"></label>
            <input asp-for="OffsetTop" class="form-control" placeholder="Offset boven" autocomplete="off"/>
        </div>
    </div>
</div>


<script>
    
</script>