AddressCollector/Controllers/PrintController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Security.Claims;
using AddressCollector.Data.Auth;
using AddressCollector.Data.Repositories.Interfaces;
using AddressCollector.Models;
using AddressCollector.Shared;
using AddressCollector.ViewModels;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using PdfSharp;
using PdfSharp.Drawing;
using PdfSharp.Pdf;

namespace AddressCollector.Controllers
{
    
    public class PrintController : Controller
    {
        private readonly IAddressRepository _addressRepository;
        private readonly ICountryRepository _countryRepository;
        private readonly IMapper _mapper;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IEnvelopeRepository _envelopeRepository;
        private PdfDocument _document;
        
        public PrintController(IAddressRepository addressRepository, 
                               ICountryRepository countryRepository,
                               IEnvelopeRepository envelopeRepository,
                               IMapper mapper, 
                               UserManager<ApplicationUser> userManager)
        {
            _addressRepository = addressRepository;
            _countryRepository = countryRepository;
            _envelopeRepository = envelopeRepository;
            _mapper = mapper;
            _userManager = userManager;
        }
        
        [Authorize(Roles="Administrator, Ondernemer")]
        // GET: /<controller>/
        public IActionResult Index(string klantId)
        {
            var model = new PrintViewModel();
            model.Adressen = new List<AddressViewModel>();

            model.Klanten = User.IsInRole("Administrator") ? _userManager.Users.ToList() : _userManager.Users.Where(x => x.OndernemerId == User.FindFirstValue(ClaimTypes.NameIdentifier)).ToList();

            ViewBag.Envelopes = _envelopeRepository.GetEnvelopesByOndernemerId(User.FindFirstValue(ClaimTypes.NameIdentifier))
                .OrderBy(c => c.Naam)
                .ToList()
                .Select(c => new SelectListItem()
                {
                    Text = c.Naam,
                    Value = c.Id.ToString()
                })
                .ToList();

            if (!string.IsNullOrEmpty(klantId))
            {
                model.Adressen = _mapper.Map<List<AddressViewModel>>(_addressRepository.GetAddressesByKlantId(klantId));
                foreach (var address in model.Adressen)
                {
                    address.Land = _mapper.Map<CountryViewModel>(_countryRepository.GetById(address.LandId));
                }
                return View(model);
            }
            return View(model);
        }

        [Authorize(Roles="Administrator, Ondernemer")]
        public IActionResult PrintAddresses(string klantId, int envelopeId)
        {
            var envelope = _mapper.Map<EnvelopeViewModel>(_envelopeRepository.GetEnvelopeById(envelopeId));
            var addresses = _mapper.Map<List<AddressViewModel>>(_addressRepository.GetAddressesByKlantId(klantId));

            if (addresses.Any())
            {
                // Create new PDF document
                _document = CreatePdf();

                foreach (var address in addresses)
                {
                    // Create new page
                    var page = CreatePdfPage(envelope.Breedte, envelope.Lengte); //document.AddPage();
                    // Create address
                    CreateAddress(page, address, envelope);
                }

                //(var i = 0; i < addresses.Count; i++)
                //{
                //    // Create new page
                //    var page = CreatePdfPage(document); //document.AddPage();
                //    //page.Size = PageSize.A5;
                //    //page.Orientation = PageOrientation.Landscape;
                //    //page.Width = XUnit.FromMillimeter(170);
                //    //page.Height = XUnit.FromMillimeter(170);
            
                //    // Create address

                //    XGraphics gfx = XGraphics.FromPdfPage(page);
                //    gfx.RotateAtTransform(270,new XPoint(170,270));
                //    // Create a font
                //    XFont font = new XFont("Times New Roman", 16, XFontStyle.Regular);

                //    //get address for test
                //    var address = _addressRepository.GetAddressById(i + 6);
                //    var naam = string.Concat(address.Voornaam, address.Tussenvoegsel != null ? " " + address.Tussenvoegsel : " ", address.Achternaan); 
                //    // Draw the text
                //    gfx.DrawString(string.Concat(address.Voornaam, address.Tussenvoegsel != null ? " " + address.Tussenvoegsel  + " " : " ", address.Achternaan), font, XBrushes.Black, new XRect(100, 40, page.Width, page.Height), XStringFormats.CenterLeft);
                //    gfx.DrawString(string.Concat(address.Straat, " ", address.Huisnummer, " ", address.HuisnummerToevoeging), font, XBrushes.Black, new XRect(100, 60, page.Width, page.Height), XStringFormats.CenterLeft);
                //    gfx.DrawString(string.Concat(address.Postcode, "  ", address.Plaats), font, XBrushes.Black, new XRect(100, 80, page.Width, page.Height), XStringFormats.CenterLeft);
                //    if (address.LandId != Constants.DefaultCountryNlId)
                //    {
                //        gfx.DrawString(string.Concat(_countryRepository.GetById(address.LandId)), font, XBrushes.Black, new XRect(100, 100, page.Width, page.Height), XStringFormats.CenterLeft);
                //    }

                //}

                // Send PDF to browser
                var stream = new MemoryStream();
                
                _document.Save(stream, false);
                Response.Clear();
                Response.ContentType = "application/pdf";
                Response.Headers.Add("content-length", stream.Length.ToString());
                
                return File(stream, "application/pdf", "adressen.pdf");
            }

            return RedirectToAction("Index");
        }

        public IActionResult PrintAddress(int addressId, int envelopeId)
        {
            var envelope = _mapper.Map<EnvelopeViewModel>(_envelopeRepository.GetEnvelopeById(envelopeId));
            //get address
            var address = _mapper.Map<AddressViewModel>(_addressRepository.GetAddressById(addressId));

            // Create new PDF document
            _document = CreatePdf();
            // Create new page
            var page = CreatePdfPage(envelope.Breedte, envelope.Lengte); //document.AddPage();
            // Create address
            CreateAddress(page, address, envelope);
            // Send PDF to browser
            var stream = new MemoryStream();
                
            _document.Save(stream, false);
            Response.Clear();
            Response.ContentType = "application/pdf";
            Response.Headers.Add("content-length", stream.Length.ToString());
                
            return File(stream, "application/pdf", "adressen.pdf");
        }


        //public IActionResult PrintOrder()
        //{
        //    try
        //    {
                

        //        for (int i = 0; i < 1; i++)
        //        {
        //            // Create new page
        //            PdfPage page = document.AddPage();
        //            page.Size = PageSize.A5;
        //            page.Orientation = PageOrientation.Landscape;
        //            page.Width = XUnit.FromMillimeter(170);
        //            page.Height = XUnit.FromMillimeter(170);
                
        //            // Create graphics object and draw clock
        //            XGraphics gfx = XGraphics.FromPdfPage(page);
        //            gfx.RotateAtTransform(270,new XPoint(170,270));
        //            // Create a font
        //            XFont font = new XFont("Times New Roman", 16, XFontStyle.Regular);

        //            //get address for test
        //            var address = _addressRepository.GetAddressById(i + 6);
        //            var naam = string.Concat(address.Voornaam, address.Tussenvoegsel != null ? " " + address.Tussenvoegsel : " ", address.Achternaan); 
        //            // Draw the text
        //            gfx.DrawString(string.Concat(address.Voornaam, address.Tussenvoegsel != null ? " " + address.Tussenvoegsel  + " " : " ", address.Achternaan), font, XBrushes.Black, new XRect(100, 40, page.Width, page.Height), XStringFormats.CenterLeft);
        //            gfx.DrawString(string.Concat(address.Straat, " ", address.Huisnummer, " ", address.HuisnummerToevoeging), font, XBrushes.Black, new XRect(100, 60, page.Width, page.Height), XStringFormats.CenterLeft);
        //            gfx.DrawString(string.Concat(address.Postcode, "  ", address.Plaats), font, XBrushes.Black, new XRect(100, 80, page.Width, page.Height), XStringFormats.CenterLeft);
        //            if (address.LandId != Constants.DefaultCountryNlId)
        //            {
        //                gfx.DrawString(string.Concat(_countryRepository.GetById(address.LandId)), font, XBrushes.Black, new XRect(100, 100, page.Width, page.Height), XStringFormats.CenterLeft);
        //            }

        //        }

                
        //        //voor vierkante enveloppen begin

        //        //// Create new page
        //        //PdfPage page = document.AddPage();
        //        //page.Size = PageSize.A5;
        //        //page.Width = XUnit.FromMillimeter(170);
        //        //page.Height = XUnit.FromMillimeter(170);
                
        //        //// Create graphics object and draw clock

AddressCollector/Views/Shared/_Carousel.cshtml
<div class="hidden-xs row carousel-holder">
    <div class="col-md-12">
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                <li data-target="#carousel-example-generic" data-slide-to="3"></li>
                <li data-target="#carousel-example-generic" data-slide-to="4"></li>
            </ol>
            <div class="carousel-inner">
                <div class="item active">
                    <img class="slide-image img-responsive" src="~/Images/carousel1.jpg" alt="">
                </div>
                <div class="item">
                    <img class="slide-image img-responsive" src="~/Images/carousel2.jpg" alt="">
                </div>
                <div class="item">
                    <img class="slide-image img-responsive" src="~/Images/carousel3.jpg" alt="">
                </div>
                <div class="item">
                    <img class="slide-image img-responsive" src="~/Images/carousel4.jpg" alt="">
                </div>
                <div class="item">
                    <img class="slide-image img-responsive" src="~/Images/carousel5.jpg" alt="">
                </div>
            </div>
            <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
            </a>
            <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
            </a>
        </div>
    </div>
</div>
<div class="visible-xs row">
    <div class="col-md-12">
        @*<img class="slide-image img-responsive" src="~/Images/Logo-Thijs-Uitvaartzorg.gif" alt="">*@
        <img class="slide-image img-responsive" src="~/Images/carousel1_small.jpg" alt="">
    </div>
</div>

AddressCollector/Views/Shared/_Layout.cshtml
@using AddressCollector.Data.Auth
@using Microsoft.AspNetCore.Authorization
@inject SignInManager<ApplicationUser> SignInManager
@inject IAuthorizationService AuthorizationService
@inject UserManager<ApplicationUser> UserManager
<!DOCTYPE html>

<html>
<head>

    <environment include="Development">
        <meta name="viewport" content="width=device-width" />
        <title>@ViewBag.Title</title>
        <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro">
        <link href="~/lib/bootstrap/css/bootstrap.css" rel="stylesheet" />
        <script src="~/lib/jquery/jquery.js"></script>
        <script src="~/lib/bootstrap/js/bootstrap.js"></script>
        <link href="~/lib/font-awesome/css/all.css" rel="stylesheet" />
        <link href="~/Content/site.css" rel="stylesheet" />
    </environment>
    <environment exclude="Development">
        <meta name="viewport" content="width=device-width" />
        <title>@ViewBag.Title</title>
        <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro">
        <link href="~/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
        <script src="~/lib/jquery/jquery.min.js"></script>
        <script src="~/lib/bootstrap/js/bootstrap.min.js"></script>
        <link href="~/lib/font-awesome/css/all.min.css" rel="stylesheet" />
        <link href="~/Content/site.css" rel="stylesheet" />
    </environment>

</head>
<body>
<div class="container">

    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle test" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><a asp-controller="Home" asp-action="Index"><img class="img-responsive" alt="Thijs Uitvaartzorg" src="~/Images/Logo-Thijs-Uitvaartzorg.gif" /></a></li>

                    @if (SignInManager.IsSignedIn(User))
                    {
                        <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                        @await Component.InvokeAsync("AddressMenu")
                            @*@await Component.InvokeAsync("CategoryMenu")*@
                            @*<li><a asp-controller="Contact" asp-action="Index">Contact</a></li>*@
                            @*@await Component.InvokeAsync("ShoppingCartSummary")*@
                    }

                    @if (SignInManager.IsSignedIn(User) && (User.IsInRole("Administrator") || User.IsInRole("Ondernemer")))
                    {
                        <li><a asp-controller="Print" asp-action="Index">Uitvoer</a></li>
                        @await Component.InvokeAsync("AdminMenu")
                    }

                    @await Html.PartialAsync("_LoginPartial")
                    @*<partial name="_LoginPartial" />*@
                </ul>
            </div>
        </div>
    </nav>

    <div class="row">
        <div class="col-md-12">
            @RenderBody()
        </div>
    </div>
    @RenderSection("Scripts", required: false)
</div>
</body>
</html>
<footer></footer>